name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        apt-get install python3-setuptools
        python3 -m pip install --upgrade pip
        pip3 install PyPDF2 setuptools

    - name: Run Tests
      env:
        MEDIAPART_USER_NAME: ${{ secrets.MEDIAPART_USER_NAME }}
        MEDIAPART_USER_PASSWORD: ${{ secrets.MEDIAPART_USER_PASSWORD }}
      run: |
        python3 -m unittest
